apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unikorn-baremetal-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
  annotations:
    {{- include "unikorn.ingress.clusterIssuer.annotations" . | nindent 4 }}
    {{- include "unikorn.ingress.mtls.annotations" . | nindent 4 }}
    {{- if (include "unikorn.ingress.externalDNS" .) }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "unikorn.baremetal.host" . }}
    {{- end }}
spec:
  {{- with $ingress := .Values.ingress }}
  {{- if $ingress.class }}
  ingressClassName: {{ $ingress.class }}
  {{- end }}
  {{- end }}
  # For development you will want to add these names to /etc/hosts for the ingress
  # endpoint address.
  tls:
  - hosts:
    - {{ include "unikorn.baremetal.host" . }}
    secretName: unikorn-baremetal-server-ingress-tls
  rules:
  - host: {{ include "unikorn.baremetal.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unikorn-baremetal-server
            port:
              name: http
