apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-baremetal-cluster-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Manage baremetal clusters (my job).
- apiGroups:
  - unikorn-cloud.org
  resources:
  - baremetalclusters
  verbs:
  - list
  - get
  - patch
  - watch
  - update
- apiGroups:
  - unikorn-cloud.org
  resources:
  - baremetalclusters/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
# ArgoCD integration.
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - list
  - get
  - watch
  - patch
  - delete
# ArgoCD integration (access to API secret).
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - create
  - patch
  - delete
