apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-baremetal-cluster-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-baremetal-cluster-controller
  template:
    metadata:
      labels:
        app: unikorn-baremetal-cluster-controller
    spec:
      containers:
      - name: unikorn-baremetal-cluster-controller
        image: {{ include "unikorn.baremetalClusterControllerImage" . }}
        args:
        {{- include "unikorn.identity.flags" . | nindent 8 }}
        {{- include "unikorn.region.flags" . | nindent 8 }}
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        - --client-certificate-namespace={{ .Release.Namespace }}
        - --client-certificate-name=unikorn-baremetal-client-certificate
        ports:
        - name: prometheus
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-baremetal-cluster-controller
      securityContext:
        runAsNonRoot: true
